squares = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]
print(squares[2:6])
print(squares[3:8])
print(squares[0:1])
print(squares[:0])
print(squares[0:])
print(len(squares))
print(squares[9])
print(squares[9:])
print(squares[9:9])
print("string"[0])
print("string"[:0])
print("string"[0:0])
print("string"[0:1])
print("string"[0:2])
print("string"[0:])
print("string"[0:6])
print("string"[5:5])
print("string"[5:6])
print("string"[6:6])
print("string"[7:6])
# If the first int >= the second int, the output will be blank.(string list)
